jwt:
  header: Authorization
  prefix: Bearer
  accessExpiration: 3600
  refreshExpiration: 604800
  secretKey: ${JWT_SECRET_KEY}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  #
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

redis:
  host: localhost
  port: 6379

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      practice-images : ${PRACTICE_IMAGES_FOLDER}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}